# Generated by Django 3.0.3 on 2020-02-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='href',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='Ссылка'),
        ),
    ]
